SAP/ui5-fs

lib/AbstractReader.js, lib/DuplexCollection.js, lib/ReaderCollection.js, lib/ReaderCollectionPrioritized.js, lib/Resource.js, lib/adapters/AbstractAdapter.js, lib/adapters/FileSystem.js, lib/adapters/Memory.js, lib/tracing/traceSummary.js, package-lock.json, package.json, test/lib/AbstractReader.js, test/lib/AbstractReaderWriter.js, test/lib/DuplexCollection.js, test/lib/ReaderCollection.js, test/lib/Resource.js, test/lib/resources.js, test/lib/tracing/traceSummary.js
While writing the tests, also JSDoc of the implemented methods had to be adapted.
=> Increase test coverage for fs module

.travis.yml, package.json
Ignore push builds. This should reduce the number of comments Coveralls adds to PRs
=> Coveralls: Only send PR build result

index.js, test/lib/fsInterface.js, test/lib/glob.js
BREAKING CHANGE: Adapters "AbstractAdapter", "FileSystem" and "Memory" used to be accessible via the top-level export of index.js (example: require("@ui5/project").FileSystem). This is no longer possible. Adapters are now grouped in the top-level object "adapters" and can be accessed from there (example: require("@ui5/project").adapters.FileSystem).
=> [BREAKING] index.js export: Remove top-level access to adapters

lib/adapters/AbstractAdapter.js, lib/adapters/FileSystem.js, lib/adapters/Memory.js, package-lock.json, package.json
Currently the only possible option should be "nodir".
This resolves possible inconsistencies when calling FileSystem and
Memory adapters with identical options containing more than "nodir".
Before, FS passed options to the glob module as a whole while Memory
only passed certain options.
This will also make it easier to upgrade to globby 8.x (see https://github.com/SAP/ui5-fs/pull/67)
=> [INTERNAL] FS Adapter: Stop passing byGlob options directly to globby

package-lock.json, package.json
dir-glob is a transitive dependency of globby ("dir-glob": "^2.0.0").
Some of our tests ("GLOB root directory" and "GLOB (normalized) root
directory (=> fs root)") are failing when using dir-glob v2.2.0.
Therefore pinning it to v2.0.0 for the time being.
This came up in our preflight tests which ignore the package-lock.json:
npm install --no-shrinkwrap --no-package-lock
Note: This is unrelated to https://github.com/SAP/ui5-fs/pull/71
Tests were still failing after reverting that change.
Moreover, this is also reproducible on Git tag v0.2.0.
=> [DEPENDENCY] Pin dir-glob to v2.0.0

test/lib/DuplexCollection.js, test/lib/ReaderCollection.js, test/lib/Resource.js
The Buffer constructor used in some of our recently added tests
(https://github.com/SAP/ui5-fs/pull/56 is deprecated. One should
use Buffer.from(string) instead.
Details:
https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
=> [INTERNAL] Tests: Replace deprecated Buffer constructor calls

package.json
Follow up of https://github.com/SAP/ui5-fs/pull/73
To pin a transitive dependency when using Yarn, "resolutions" need to be
used.
=> [DEPENDENCY] Yarn: Pin dir-glob dependency to v2.0.0

lib/adapters/AbstractAdapter.js, lib/adapters/FileSystem.js, lib/adapters/Memory.js, test/lib/adapters/FileSystem.js, test/lib/adapters/Memory.js, test/lib/glob.js, test/lib/resources.js
Work in progress. Required fix for some cases of https://github.com/SAP/ui5-project/pull/4
=> [FIX] AbstractAdapter: GLOB match virtual dir fragments

package-lock.json, package.json, test/lib/AbstractReader.js, test/lib/AbstractReaderWriter.js, test/lib/DuplexCollection.js, test/lib/ReaderCollection.js, test/lib/Resource.js, test/lib/adapters/FileSystem_read.js, test/lib/adapters/FileSystem_write.js, test/lib/adapters/Memory_read.js, test/lib/adapters/Memory_write.js, test/lib/fsInterface.js, test/lib/glob.js, test/lib/resources.js, test/lib/tracing/traceSummary.js
Relevant changelogs:
https://github.com/avajs/ava/releases/tag/v1.0.1
https://github.com/avajs/ava/releases/tag/v2.0.0
Relevant changes:
- AVA now requires at least Node.js 8.9.4. We require only 8.5.
However, since this is a devDependency I guess we can live with that.
- t.throws() does not accept promises anymore. Use t.throwsAsync()
- Test titles now must be unique
=> [INTERNAL] Bump ava to 2.0.0

lib/fsInterface.js, package-lock.json, package.json, test/fixtures/fsInterface/foo.txt, test/lib/fsInterface.js
This resolves issues with the JSDoc build (especially the `generateApiIndex` task) on Windows.
fs functions can be called with non-POSIX paths on non-POSIX systems.
fsInterface should handle this correctly by converting any non-POSIX
paths to POSIX for further UI5 FS internal processing.
=> [FIX] fsInterface: Handle non-POSIX paths correctly

lib/resourceFactory.js, test/lib/resources.js
BREAKING CHANGE:
Remove deprecated parameter "useNamespaces" from
method "resourceFactory.createCollectionsForTree".
Use parameter "getVirtualBasePathPrefix" instead.
=> [BREAKING] Remove deprecated parameter useNamespaces

test/lib/resources.js
Flag was added with https://github.com/SAP/ui5-project/pull/287
Tests are not failing. This is just for consistency reasons and to
prevent future issues.
=> [INTERNAL] Adapt tests to new project._isRoot flag

lib/Resource.js, lib/adapters/Memory.js, test/lib/adapters/Memory_read.js
**Thank you for your contribution!** 🙌
To get it merged faster, kindly review the checklist below:
+ Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#how-to-contribute) section
=> [FIX] adapters/Memory: Return cloned resources

lib/Resource.js, test/lib/Resource.js, test/lib/adapters/FileSystem_read.js
If a resource does not have any content (empty string), the stream still can be retrieved.
Before the error `Resource ${this._path} has no content`
was thrown for the empty string.
Add additional test "getStream for empty file: correctly retrieved" which uses a buffer for an empty file for completeness.
=> [FIX] Resource: getStream for empty string

lib/Resource.js, test/lib/Resource.js
Ensure statInfo.size is always set when resource's content is modified.
=> [FIX] Resource: Keep stats size up to date

index.js, jsdoc-plugin-ignore-ts-import/index.js, jsdoc-plugin.js, jsdoc.json
Lazy-loading breaks the automatic type definition detection from
TypeScript. Therefore we need to manually declare the exported types.
=> [FIX] TypeScript type definition support

lib/Resource.js, test/lib/Resource.js
`Stats.size` was not set for a stream.
To ensure Resource's size can be retrieved for:
- stream
- string
- buffer
async method is introduced which uses `Resource#getBuffer` to
ensure that size retrieval works for all content types.
followup of #253
=> [FIX] Resource#getSize: Retrieve Resource's size

lib/Resource.js, lib/adapters/Memory.js, test/lib/adapters/Memory_read.js
Reverts https://github.com/SAP/ui5-fs/pull/235 as discussed in todays planning.
We don't want to release https://github.com/SAP/ui5-fs/pull/235 without https://github.com/SAP/ui5-fs/pull/259. However, https://github.com/SAP/ui5-fs/pull/259 breaks tests in ui5-builder and might be incompatible in general. Also it's currently not critical for us.
=> Revert "[FIX] adapters/Memory: Return cloned resources"

lib/ResourceTagCollection.js, test/lib/ResourceTagCollection.js
This can lead to issues where a custom task creates resources using a
different version of @ui5/fs. These reosurces will fail the instanceof
check that was implemented here.
Instead of checking for the class, we now validate that the resource has
a path. The path is currently the only relevant attribute for
ResourceTagCollection and mandatory for Resources.
Resolves https://github.com/SAP/ui5-fs/issues/269
=> [FIX] ResourceTagCollection: Do not validate class of resource

.eslintrc.js, package-lock.json, package.json, test/lib/DuplexCollection.js, test/lib/ReaderCollection.js, test/lib/Resource.js, test/lib/ResourceFacade.js, test/lib/WriterCollection.js, test/lib/adapters/FileSystem_read.js, test/lib/adapters/Memory_read.js, test/lib/adapters/Memory_write.js, test/lib/fsInterface.js, test/lib/glob.js, test/lib/readers/Filter.js, test/lib/readers/Link.js, test/lib/readers/Transformer.js, test/lib/resourceFactory.js, test/lib/tracing/traceSummary.js
Introducing [eslint-plugin-ava](https://github.com/avajs/eslint-plugin-ava/) to avoid common pitfalls when writing powerful ava tests.
- Add plugin to eslint config and package.json
- Restructure current code base to latest recommendations
=> [INTERNAL] use eslint-plugin-ava and cleanup test-suite

lib/Resource.js, lib/ResourceFacade.js, lib/fsInterface.js, test/lib/Resource.js, test/lib/ResourceFacade.js
Modules like the "[serveIndex](https://github.com/SAP/ui5-server/blob/e7f64dbecdafae717191ee726f7003b505dcb622/lib/middleware/serveIndex.js#L52)" middleware or the "[fsInterface](https://github.com/SAP/ui5-fs/blob/eea2464bd2a0609a7ee9f4cb17ef08871bbbfbc4/lib/fsInterface.js#L82)" currently
determine the name of a Resource by using the private `_name` attribute.
This is typically required for listing the content of a directory.
This attribute was missing from ResourceFacade, which lead to issues in
both modules.
In addition to adding the missing, private attribute. Also add a public
function getName().
=> [INTERNAL] Resource: Add getName function

.github/workflows/codeql-analysis.yml, .github/workflows/github-ci.yml, .github/workflows/reuse-compliance.yml, azure-pipelines.yml
In the main branch only workflow configurations related to the main branch are stored.
Other release branches will contain their own configuration.
**Exceptions**: 
- `dependabot.yml`: All branches triggering dependabot updates have to be maintained in the default branch "main" configuration
- `azure-pipelines.yml`: All branches triggering azure pipeline flows have to be maintained in the default branch "main" configuration.
=> [INTERNAL] Remove other than main branch workflows

lib/AbstractReader.js, test/lib/resources.js
They have been moved to resourceFactory in
https://github.com/SAP/ui5-fs/pull/438
=> [INTERNAL] AbstractReader: Remove obsolete filter and flatten methods

lib/adapters/FileSystem.js, package-lock.json, package.json, test/lib/adapters/FileSystem_write.js
The recursive option is available since Node v10.12, which makes the
use of thirdparty packages obsolete for most use cases.
=> [INTERNAL] Use native fs.mkdir instead of make-dir

lib/Resource.js, lib/adapters/Memory.js, test/lib/Resource.js, test/lib/adapters/AbstractAdapter.js, test/lib/adapters/Memory_read.js, test/lib/adapters/Memory_write.js, test/lib/resources.js
Clone resources when writing them in the memory.
JIRA: CPOUI5FOUNDATION-567
Follow-Up of https://github.com/SAP/ui5-fs/pull/259.
=> [BREAKING] Clone resources when writing in and reading from the Memory

lib/adapters/AbstractAdapter.js, test/lib/adapters/AbstractAdapter.js, test/lib/resources.js
Follow-up of https://github.com/SAP/ui5-fs/pull/448
Only perform the write operation when the path of the resource starts with the configured virtual base path of the respective adapter.
=> [BREAKING] Throw an error on write of a resource when path does not match virBasePath of the respective adapter

lib/DuplexCollection.js, lib/ReaderCollection.js, lib/ReaderCollectionPrioritized.js, lib/WriterCollection.js, test/lib/DuplexCollection.js, test/lib/ReaderCollection.js, test/lib/ReaderCollectionPrioritized.js, test/lib/WriterCollection.js
If no readers are provided, no error is thrown and no resources are returned.
This behavior was mostly already in place (and relied upon) but never fully specified.
This makes it easy to implement tasks that just want to fetch any available dependencies, even if none are available (for example if the project has no dependencies).
See also https://github.com/SAP/ui5-fs/pull/455 for the opposite approach of dissallowing collections without readers.
Also add tests for ReaderCollectionPrioritized (99% copy of the ReaderCollection tests)
=> [INTERNAL] Reader Collections: Allow for empty readers

lib/adapters/AbstractAdapter.js, test/lib/adapters/AbstractAdapter.js, test/lib/resources.js
Sadly a typo was introduced in the newly created error message. Therefore, fixing the typo with this PR.
Follow-Up of: https://github.com/SAP/ui5-fs/pull/453
=> [INTERNAL] AbstractAdapter: Correct typo in error message

lib/Resource.js, lib/adapters/Memory.js, test/lib/Resource.js
When cloning a Resource, the new Resource instance should not be associated with any project. This allows for use cases where a resource is copied from one project to another.
The problematic behavior was introduced with https://github.com/SAP/ui5-fs/pull/448 and motivated by the need of the memory adapter to clone resources while keeping the project association.
However, since memory adapters are always assigned a project, they can easily just assign that project to the cloned resource. This has been implemented in this PR.
=> [INTERNAL] Resource#clone: Omit project association

lib/adapters/FileSystem.js, lib/adapters/Memory.js
Use template literals wherever possible.
This is in prepration for @ui5/logger changes as per
https://github.com/SAP/ui5-logger/pull/353
=> [INTERNAL] Refactor log-calls

lib/Resource.js, lib/ResourceFacade.js, lib/adapters/FileSystem.js, lib/adapters/Memory.js, test/lib/Resource.js, test/lib/adapters/FileSystem_write.js, test/lib/adapters/FileSystem_write_large_file.js, test/lib/adapters/Memory_read.js, test/lib/glob.js
This allows to check whether the content of a resource has been
modified.
For example, if a build processor did not modify a resource, one could
omit writing it into the workspace resource collection. If a resource
has not been modified during the build process and has not been written
into the workspace, the FileSystem adapter can optimize the write
process, for example by using fs.copyFile.
Also in this change:
* Rename internal Resource parameter 'source' to 'sourceMetadata' and
contained flag 'modified' to 'contentModified'
* FileSystem adapter: Do not stream into the same file when writing.
Refactor related code
* Adding a test for writing large files to the same path as the source
=> [FEATURE] Resource: Add isModified method

lib/Resource.js, lib/adapters/AbstractAdapter.js, lib/adapters/FileSystem.js, lib/adapters/Memory.js, test/lib/Resource.js
This is a follow-up of https://github.com/SAP/ui5-fs/pull/472
The setBuffer/setString calls in the constructor lead to the
sourceMetadata.contentModified flag being set to true, even though the
content has not been modified. To resolve this, use the internal
setter, which does not set any modification flags.
=> [INTERNAL] Resource: Do not flag as modified during creation

lib/Resource.js, lib/ResourceFacade.js, lib/adapters/AbstractAdapter.js, lib/adapters/FileSystem.js, lib/adapters/Memory.js, lib/resourceFactory.js, test/lib/DuplexCollection.js, test/lib/ReaderCollection.js, test/lib/ReaderCollectionPrioritized.js, test/lib/Resource.js, test/lib/ResourceFacade.js, test/lib/adapters/AbstractAdapter.js, test/lib/adapters/FileSystem.js, test/lib/adapters/FileSystem_read.js, test/lib/adapters/Memory_read.js, test/lib/resourceFactory.js, test/lib/resources.js
* Resources: Resources must always have absolute paths. This was already the case in the past but is now properly validated. Resources with relative paths could lead to undetermined behavior.
* Adapters: Improve checks to make sure that resolved paths still start with the adapter base path. This should prevent path traversals outside the adapter's base path.
=> [INTERNAL] Resource/Adapters: Enforce absolute paths, resolve all paths before use

lib/adapters/FileSystem.js, lib/adapters/Memory.js, test/lib/adapters/FileSystem_read.js
AbstractAdapter#_resolveVirtualPathToBase might return an empty string
in case the root path of the adapter is matched. Therefore, adapters
must only reject the path if the method returned 'null'.
=> [INTERNAL] Adapters: Fix if-clause checking for matching base path

lib/Resource.js, test/lib/Resource.js
This ensures that the contentModified flag is tracked for all
resources, not only for those created by a FileSystem adapter.
JIRA: CPOUI5FOUNDATION-467
=> [INTERNAL] Resource: Always set internal sourceMetadata attribute

package-lock.json, package.json, test/lib/adapters/FileSystem_write.js, test/lib/resources.js
`chai-fs` is not compatible with latest version of `chai`. Therefore its easier to get rid of chai completely.
JIRA: CPOUI5FOUNDATION-801
=> [INTERNAL] Refactor tests to get rid of chai and chai-fs

lib/DuplexCollection.js, test/lib/DuplexCollection.js
BREAKING CHANGE:
`byGlobSource` method is removed from `DuplexCollection`
JIRA: CPOUI5FOUNDATION-802
Relates to: https://github.com/SAP/ui5-tooling/issues/701
=> [BREAKING] DuplexCollection: remove byGlobSource method
